// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger Potion maker - OpenAPI 3.0
 *
 * Сервис изготовления зелий
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// WitchAPIService is a service that implements the logic for the WitchAPIServicer
// This service should implement the business logic for every endpoint for the WitchAPI API.
// Include any external packages or services that will be required by this service.
type WitchAPIService struct {
}

// NewWitchAPIService creates a default api service
func NewWitchAPIService() *WitchAPIService {
	return &WitchAPIService{}
}

// WitchesList - witches list
func (s *WitchAPIService) WitchesList(ctx context.Context) (ImplResponse, error) {
	// TODO - update WitchesList with the required logic for this service method.
	// Add api_witch_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Witch{}) or use other options such as http.Ok ...
	// return Response(200, []Witch{}), nil

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("WitchesList method not implemented")
}

// GetWitchByUUID - Find witch by UUID
func (s *WitchAPIService) GetWitchByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update GetWitchByUUID with the required logic for this service method.
	// Add api_witch_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Witch{}) or use other options such as http.Ok ...
	// return Response(200, Witch{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetWitchByUUID method not implemented")
}

// UpdateWitchByUUID - Update a witch in the store with form data
func (s *WitchAPIService) UpdateWitchByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update UpdateWitchByUUID with the required logic for this service method.
	// Add api_witch_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Witch{}) or use other options such as http.Ok ...
	// return Response(200, Witch{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateWitchByUUID method not implemented")
}

// DeleteWitchByUUID - Deletes a witch
func (s *WitchAPIService) DeleteWitchByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update DeleteWitchByUUID with the required logic for this service method.
	// Add api_witch_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteWitchByUUID method not implemented")
}
