// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger Potion maker - OpenAPI 3.0
 *
 * Сервис изготовления зелий
 *
 * API version: 1.0.0
 */

package openapi

type Recipe struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name"`

	BrewTimeSeconds int32 `json:"brew_time_seconds"`

	Ingredients []Ingredient `json:"ingredients"`
}

// AssertRecipeRequired checks if the required fields are not zero-ed
func AssertRecipeRequired(obj Recipe) error {
	elements := map[string]interface{}{
		"name":              obj.Name,
		"brew_time_seconds": obj.BrewTimeSeconds,
		"ingredients":       obj.Ingredients,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Ingredients {
		if err := AssertIngredientRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecipeConstraints checks if the values respects the defined constraints
func AssertRecipeConstraints(obj Recipe) error {
	for _, el := range obj.Ingredients {
		if err := AssertIngredientConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
