// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger Potion maker - OpenAPI 3.0
 *
 * Сервис изготовления зелий
 *
 * API version: 1.0.0
 */

package main

import (
	openapi2 "github.com/donskova1ex/magic_potions/openapi"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	IngredientAPIService := openapi2.NewIngredientAPIService()
	IngredientAPIController := openapi2.NewIngredientAPIController(IngredientAPIService)

	RecipeAPIService := openapi2.NewRecipeAPIService()
	RecipeAPIController := openapi2.NewRecipeAPIController(RecipeAPIService)

	WitchAPIService := openapi2.NewWitchAPIService()
	WitchAPIController := openapi2.NewWitchAPIController(WitchAPIService)

	router := openapi2.NewRouter(IngredientAPIController, RecipeAPIController, WitchAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
