// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/donskova1ex/magic_potions/internal/processors (interfaces: IngredientsLogger)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// IngredientsLogger is a mock of IngredientsLogger interface.
type IngredientsLogger struct {
	ctrl     *gomock.Controller
	recorder *IngredientsLoggerMockRecorder
}

// IngredientsLoggerMockRecorder is the mock recorder for IngredientsLogger.
type IngredientsLoggerMockRecorder struct {
	mock *IngredientsLogger
}

// NewIngredientsLogger creates a new mock instance.
func NewIngredientsLogger(ctrl *gomock.Controller) *IngredientsLogger {
	mock := &IngredientsLogger{ctrl: ctrl}
	mock.recorder = &IngredientsLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *IngredientsLogger) EXPECT() *IngredientsLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *IngredientsLogger) Error(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *IngredientsLoggerMockRecorder) Error(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*IngredientsLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *IngredientsLogger) Info(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *IngredientsLoggerMockRecorder) Info(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*IngredientsLogger)(nil).Info), varargs...)
}
